// This file is generated by Prismic local builder. Update with care!

export { default as Contact } from './Contact'
export { default as Hero } from './Hero'
export { default as TextBlock } from './TextBlock'
export { default as TwoColumns } from './TwoColumns'
