// This file is generated by Prismic local builder. Update with care!

import Contact from './Contact';
import Hero from './Hero';
import TextBlock from './TextBlock';
import TwoColumns from './TwoColumns';

export {
	Contact,
	Hero,
	TextBlock,
	TwoColumns,
};

export const components = {
	contact: Contact,
	hero: Hero,
	text_block: TextBlock,
	two_columns: TwoColumns,
};